# Generated by Django 5.2.3 on 2025-10-10 14:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_conversation_deleted_at_conversation_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, validators=[core.validators.validate_youtube_url]),
        ),
    ]
