# Generated by Django 5.2.3 on 2025-11-24 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_lesson_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at', '-updated_at'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_title_8ec32b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_categor_6c934b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_country_d8db5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_created_d4267f_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_level_061d5f_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Fecha del último mensaje', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_count',
            field=models.PositiveIntegerField(default=0, help_text='Número total de mensajes'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el usuario leyó el mensaje', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, help_text='Título de la conversación', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Contenido del mensaje'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(help_text='Conversación a la que pertenece el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True, help_text='True si es mensaje del usuario, False si es de la IA'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', '-created_at'], name='core_blogpo_is_publ_56cd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', '-created_at'], name='core_blogpo_categor_207ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author'], name='core_blogpo_author__b8b262_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='core_commen_post_id_0d7c44_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='core_commen_author__87794d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-last_message_at'], name='core_conver_user_id_a43be2_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['category', '-created_at'], name='core_forump_categor_37de83_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author'], name='core_forump_author__646e97_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['is_pinned', '-created_at'], name='core_forump_is_pinn_bdf8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='core_messag_convers_d2b392_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_user'], name='core_messag_is_user_beae18_idx'),
        ),
    ]
