# Generated by Django 5.2.3 on 2025-10-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_lesson_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(help_text='ID del Payment Intent en Stripe', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto en USD', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Nombre del plan (ej: Premium, Pro)', max_length=100)),
                ('description', models.TextField(help_text='Descripción del plan y sus beneficios')),
                ('plan_type', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, help_text='ID del precio en Stripe', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=list, help_text='Lista de características del plan')),
                ('max_lessons', models.IntegerField(blank=True, help_text='Máximo de lecciones que puede crear', null=True)),
                ('max_expressions', models.IntegerField(blank=True, help_text='Máximo de expresiones por lección', null=True)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('has_audio_download', models.BooleanField(default=False)),
                ('has_certificates', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan de Subscripción',
                'verbose_name_plural': 'Planes de Subscripción',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(help_text='ID de subscripción en Stripe', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('canceled', 'Cancelada'), ('past_due', 'Vencida'), ('incomplete', 'Incompleta'), ('trialing', 'En período de prueba')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subscripción de Usuario',
                'verbose_name_plural': 'Subscripciones de Usuarios',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_title_8ec32b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_categor_6c934b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_country_d8db5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_created_d4267f_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_level_061d5f_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usersubscription'),
        ),
    ]
