# Generated by Django 5.2.3 on 2026-03-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
