# Generated by Django 5.2.3 on 2026-03-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='video_explicativo_id',
            field=models.CharField(blank=True, default='BnC2zl5Y-ds', help_text='ID del video de YouTube (ej: dQw4w9WgXcQ) para reproducir en la página', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='video_explicativo_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=BnC2zl5Y-ds', help_text='URL del video que explica qué es SlangSpot Latino', max_length=500),
        ),
    ]
