# Generated by Django 5.2.3 on 2026-03-26 19:05

from django.db import migrations


def update_default_video(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    # Actualiza todos los Settings existentes para que apunten al nuevo id
    SiteSettings.objects.update(
        video_explicativo_id="BnC2zl5Y-ds",
        video_explicativo_url="https://www.youtube.com/watch?v=BnC2zl5Y-ds"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_sitesettings_video_explicativo_id_and_more'),
    ]

    operations = [
        migrations.RunPython(update_default_video),
    ]
