# Generated by Django 5.2.3 on 2026-03-31 00:05

import cloudinary_storage.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_update_sitesettings_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='expression_audio/', validators=[core.validators.validate_file_size, core.validators.validate_audio_extension]),
        ),
    ]
